### ISSUE TITLE
review robotics reporting lesson 

### ISSUE THREAD

**Issue by CaitlinBate** [ocean-tracking-network/otn_field_reporting_standards#14]
https://ocean-tracking-network.github.io/otn_field_reporting_standards/04-ROV/index.html

add comments here ill make the edits

**Comment by jdpye** [comment]
sure you don't want a PR?

**Comment by CaitlinBate** [comment]
im editing all the lessons now (adding pics etc) so might just create more conflicts lol

**Comment by jdpye** [comment]
Understood.

**Comment by jdpye** [comment]
## Record Keeping for Robotics Missions

ROV camera and remote sensing data are important contributors to our understanding of biological presence or absence in difficult-to-sample parts of the ocean. It can also make important contributions to habitat mapping or species composition/interaction observations, even when this was not the intended aim of the deployment. This creates an obligation to our many partners as well as our funders to record and document all ROV missions thoroughly for future re-use of this valuable data. This will include proper archiving of all collected data, video footage and other samples along with complete metadata to give temporal and geographical context. 

Operators are also responsible for the constant verification and re-evaluation of the workflow to ensure we continue to safely and productively meet these obligations while adhering to the latest in industry reporting standards.

### Current OTN ROV Reporting Requirements

The latest set of instructions for ROV/SSS Reporting will always be available on the [Field Ops GitLab](https://gitlab.oceantrack.org/otnfield/OTN_Field_Ops/-/wikis/ROV%20and%20SSS%20Reporting).

### Workflow for Reporting/Documentation:
1. When a request for an ROV project is received and scoped, a project needs to be entered into the [Loaner Operations project in Podio](https://podio.com/ocean-tracking-network-new/operations/apps/robotics-projects). This information can then be used by the Project Management team to track the partnerships formed and any legal agreements required.
2. Once an ROV mission has been completed, the following information must be added by the Operator to [this OneDrive folder](https://dalu-my.sharepoint.com/:f:/g/personal/otndc_dal_ca/EnneuV4kB1hIlIIoeL1TbE0BAZH9OsCR--ClfC4u3SMffA?e=70KJFN). Direct uploading is necessary because the size of most of these files precludes them being emailed.
	- Data files from the instruments
	- Video files from the instruments
	- Any video clips that have been deemed relevant/interesting, or notes describing any significant video sections (for the Communications team).
	- GPS trackfile of the flightpath (if available), or start/end coordinates for the mission
3. Once an ROV mission has been completed, the following information must be emailed to OTNDC@Dal.ca or posted in the relevant Data Portal folder.
	- [Mission report](https://members.oceantrack.org/data/data-collection/otn-mission-report.xls)
	- Deployment metadata **TODO: add template**

Missions completed for other partners will get their own project created in the OTN database, while all other OTN-led projects will be added to an OTN-Robotics catch-all project.

### Current OTN SSS Reporting Requirements

The latest instructions for ROV/SSS Reporting will always be available on the [Field Ops GitLab](https://gitlab.oceantrack.org/otnfield/OTN_Field_Ops/-/wikis/ROV%20and%20SSS%20Reporting).

1. When a request for a sidescan project is received and scoped, a project needs to be entered into the [Loaner Operations project in Podio](https://podio.com/ocean-tracking-network-new/operations/apps/robotics-projects). This information can then be used by the Project Management team to track the partnerships formed and any legal agreements required.
2. Once a sidescan mission has been completed, the following information must be added by the Operator to [this OneDrive folder](https://dalu-my.sharepoint.com/:f:/g/personal/otndc_dal_ca/EnneuV4kB1hIlIIoeL1TbE0BAZH9OsCR--ClfC4u3SMffA?e=70KJFN)
	- Raw data files from the instrument
	- GPS trackfile of the flightpath
	- any processed SSS files/images
3. Once a SSS mission has been completed, the following information must be emailed to OTNDC@Dal.ca (or posted in the relevant Data Portal folder)
	- [Mission report](https://members.oceantrack.org/data/data-collection/otn-mission-report.xls)
	- Deployment metadata **TODO: add template**

Missions completed for other partners will get their own project created in the OTN database, while all other OTN-lead projects will be added to an OTN-Robotics catch-call project.

## Establishing Standards Based on Industry Practices

OTNDC's questions for the field team include:

- What are the standard data files and formats that are currently collected by OTN ROV or SSS missions?
- What extra information is generally important for post-processing / data analysis of these files? Instrument programming, weather conditions, oceanographic information?
- What do most professionals use to add geographic context to ROV/SSS missions? GPS trackfiles, start/end coordinates?
- Are there standard reporting templates in use by our partners that we can or should adopt?

We are excited to expand our robotics fleet and are keen and willing to change our expectations based on the experience of professionals.
